export interface PageEmoji {
  char: string
  /** Accessible name of the picker button. */
  name: string
}

/** 60 icons for study pages: learning, tech, goals, focus, life. Keep the count a multiple of 10. */
export const PAGE_EMOJI: readonly PageEmoji[] = [
  { char: '🎓', name: 'Graduation cap' },
  { char: '📚', name: 'Books' },
  { char: '📖', name: 'Open book' },
  { char: '📝', name: 'Memo' },
  { char: '✏️', name: 'Pencil' },
  { char: '🧠', name: 'Brain' },
  { char: '💡', name: 'Light bulb' },
  { char: '🔬', name: 'Microscope' },
  { char: '🧪', name: 'Test tube' },
  { char: '🔭', name: 'Telescope' },
  { char: '🧮', name: 'Abacus' },
  { char: '📐', name: 'Triangular ruler' },
  { char: '💻', name: 'Laptop' },
  { char: '⌨️', name: 'Keyboard' },
  { char: '🖥️', name: 'Desktop computer' },
  { char: '🛠️', name: 'Hammer and wrench' },
  { char: '⚙️', name: 'Gear' },
  { char: '🔐', name: 'Locked with key' },
  { char: '🌐', name: 'Globe with meridians' },
  { char: '📡', name: 'Satellite antenna' },
  { char: '🤖', name: 'Robot' },
  { char: '🧩', name: 'Puzzle piece' },
  { char: '🎯', name: 'Direct hit' },
  { char: '🏆', name: 'Trophy' },
  { char: '🥇', name: 'First place medal' },
  { char: '🚀', name: 'Rocket' },
  { char: '🔥', name: 'Fire' },
  { char: '⚡', name: 'High voltage' },
  { char: '📈', name: 'Chart increasing' },
  { char: '✅', name: 'Check mark' },
  { char: '🏁', name: 'Chequered flag' },
  { char: '⭐', name: 'Star' },
  { char: '🌟', name: 'Glowing star' },
  { char: '💪', name: 'Flexed biceps' },
  { char: '⏱️', name: 'Stopwatch' },
  { char: '⏳', name: 'Hourglass' },
  { char: '📅', name: 'Calendar' },
  { char: '🗓️', name: 'Spiral calendar' },
  { char: '🔔', name: 'Bell' },
  { char: '🧘', name: 'Person in lotus position' },
  { char: '🎧', name: 'Headphones' },
  { char: '☕', name: 'Hot beverage' },
  { char: '🌱', name: 'Seedling' },
  { char: '🌿', name: 'Herb' },
  { char: '🌳', name: 'Tree' },
  { char: '🏠', name: 'House' },
  { char: '💼', name: 'Briefcase' },
  { char: '📊', name: 'Bar chart' },
  { char: '📁', name: 'File folder' },
  { char: '🗂️', name: 'Card index dividers' },
  { char: '📌', name: 'Pushpin' },
  { char: '🔖', name: 'Bookmark' },
  { char: '🧭', name: 'Compass' },
  { char: '🗺️', name: 'World map' },
  { char: '🌙', name: 'Crescent moon' },
  { char: '☀️', name: 'Sun' },
  { char: '🌊', name: 'Water wave' },
  { char: '⛰️', name: 'Mountain' },
  { char: '🎨', name: 'Artist palette' },
  { char: '💰', name: 'Money bag' },
]
